[2025-07-26T07:32:56.460+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T07:32:58.311+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T18:00:00+00:00 [queued]>
[2025-07-26T07:32:58.533+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T18:00:00+00:00 [queued]>
[2025-07-26T07:32:58.533+0700] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2025-07-26T07:32:58.813+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_songplays_fact_table> on 2025-07-25 18:00:00+00:00
[2025-07-26T07:32:58.819+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_songplays_fact_table', 'scheduled__2025-07-25T18:00:00+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpmpr5lmzl']
[2025-07-26T07:32:58.821+0700] {standard_task_runner.py:91} INFO - Job 347: Subtask load_songplays_fact_table
[2025-07-26T07:32:58.821+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1683) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T07:32:58.822+0700] {standard_task_runner.py:63} INFO - Started process 1684 to run task
[2025-07-26T07:33:01.554+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T18:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T07:33:05.849+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T18:00:00+00:00'
[2025-07-26T07:33:05.850+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T07:33:07.697+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T07:33:08.336+0700] {sql.py:470} INFO - Running statement: 
    INSERT INTO songplays (
        songplay_id, start_time, userid, level,
        song_id, artist_id, sessionid, location, useragent
    )
    SELECT
        md5(CAST(events.sessionid AS TEXT) || CAST(events.start_time AS TEXT)) AS songplay_id,
        events.start_time, 
        events.userid, 
        events.level, 
        songs.song_id,
        songs.artist_id, 
        events.sessionid, 
        events.location, 
        events.useragent
    FROM (
        SELECT TIMESTAMP 'epoch' + ts/1000 * interval '1 second' AS start_time, *
        FROM staging_events
        WHERE page='NextSong'
    ) events
    LEFT JOIN staging_songs songs
    ON events.song = songs.title
        AND events.artist = songs.artist_name
        AND events.length = songs.duration
, parameters: None
[2025-07-26T07:33:08.466+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T07:33:08.467+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 98, in load_songplays_table
    execute_sql(sql_queries.SqlQueries.songplay_table_insert)
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 17, in execute_sql
    result = hook.run(sql_statement)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "songplay_id" of relation "songplays" does not exist
LINE 3:         songplay_id, start_time, userid, level,
                ^

[2025-07-26T07:33:09.190+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_local_postgres_pipeline, task_id=load_songplays_fact_table, run_id=scheduled__2025-07-25T18:00:00+00:00, execution_date=20250725T180000, start_date=20250726T003258, end_date=20250726T003309
[2025-07-26T07:33:10.004+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 347 for task load_songplays_fact_table (column "songplay_id" of relation "songplays" does not exist
LINE 3:         songplay_id, start_time, userid, level,
                ^
; 1684)
[2025-07-26T07:33:10.047+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T07:33:10.937+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T07:33:11.070+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
