[2025-07-26T06:59:04.841+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T06:59:06.603+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.run_data_quality_check manual__2025-07-25T18:12:48.278884+00:00 [queued]>
[2025-07-26T06:59:06.786+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.run_data_quality_check manual__2025-07-25T18:12:48.278884+00:00 [queued]>
[2025-07-26T06:59:06.787+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-26T06:59:07.010+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_quality_check> on 2025-07-25 18:12:48.278884+00:00
[2025-07-26T06:59:07.019+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'run_data_quality_check', 'manual__2025-07-25T18:12:48.278884+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpgu90bw4m']
[2025-07-26T06:59:07.020+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=785) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T06:59:07.021+0700] {standard_task_runner.py:91} INFO - Job 305: Subtask run_data_quality_check
[2025-07-26T06:59:07.021+0700] {standard_task_runner.py:63} INFO - Started process 787 to run task
[2025-07-26T06:59:09.587+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.run_data_quality_check manual__2025-07-25T18:12:48.278884+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T06:59:13.800+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='run_data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T18:12:48.278884+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T18:12:48.278884+00:00'
[2025-07-26T06:59:13.800+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T06:59:15.659+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T06:59:16.298+0700] {logging_mixin.py:188} INFO - Checking data quality for table: songplays
[2025-07-26T06:59:16.396+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T06:59:16.397+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 142, in data_quality_check
    raise ValueError(f"Data quality check failed for {table}. Table is empty!")
ValueError: Data quality check failed for songplays. Table is empty!
[2025-07-26T06:59:17.123+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=run_data_quality_check, run_id=manual__2025-07-25T18:12:48.278884+00:00, execution_date=20250725T181248, start_date=20250725T235906, end_date=20250725T235917
[2025-07-26T06:59:17.419+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 305 for task run_data_quality_check (Data quality check failed for songplays. Table is empty!; 787)
[2025-07-26T06:59:17.443+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T06:59:18.398+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T06:59:18.458+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
