[2025-07-26T07:42:45.559+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T07:42:47.257+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_artist_dim_table scheduled__2025-07-26T00:00:00+00:00 [queued]>
[2025-07-26T07:42:47.458+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_artist_dim_table scheduled__2025-07-26T00:00:00+00:00 [queued]>
[2025-07-26T07:42:47.458+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 5
[2025-07-26T07:42:47.653+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_artist_dim_table> on 2025-07-26 00:00:00+00:00
[2025-07-26T07:42:47.663+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_artist_dim_table', 'scheduled__2025-07-26T00:00:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpynq81ig4']
[2025-07-26T07:42:47.665+0700] {standard_task_runner.py:91} INFO - Job 357: Subtask load_artist_dim_table
[2025-07-26T07:42:47.666+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5104) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T07:42:47.666+0700] {standard_task_runner.py:63} INFO - Started process 5108 to run task
[2025-07-26T07:42:50.105+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_artist_dim_table scheduled__2025-07-26T00:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T07:42:56.442+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_artist_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-26T00:00:00+00:00'
[2025-07-26T07:42:56.443+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T07:42:57.257+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T07:42:58.815+0700] {sql.py:470} INFO - Running statement: 
    INSERT INTO artists (artist_id, name, location, latitude, longitude)
    SELECT DISTINCT artist_id, artist_name, artist_location, artist_latitude, artist_longitude
    FROM staging_songs
, parameters: None
[2025-07-26T07:42:58.916+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T07:42:58.918+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 104, in load_artists_table
    execute_sql(sql_queries.SqlQueries.artist_table_insert)
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 17, in execute_sql
    result = hook.run(sql_statement)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "artist_id" of relation "artists" does not exist
LINE 2:     INSERT INTO artists (artist_id, name, location, latitude...
                                 ^

[2025-07-26T07:42:59.679+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=load_artist_dim_table, run_id=scheduled__2025-07-26T00:00:00+00:00, execution_date=20250726T000000, start_date=20250726T004247, end_date=20250726T004259
[2025-07-26T07:43:00.282+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 357 for task load_artist_dim_table (column "artist_id" of relation "artists" does not exist
LINE 2:     INSERT INTO artists (artist_id, name, location, latitude...
                                 ^
; 5108)
[2025-07-26T07:43:00.320+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T07:43:01.235+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T07:43:01.278+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
