[2025-07-26T06:58:57.140+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T06:58:58.881+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.run_data_quality_check scheduled__2025-07-25T19:00:00+00:00 [queued]>
[2025-07-26T06:58:59.280+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.run_data_quality_check scheduled__2025-07-25T19:00:00+00:00 [queued]>
[2025-07-26T06:58:59.281+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-26T06:58:59.564+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_quality_check> on 2025-07-25 19:00:00+00:00
[2025-07-26T06:58:59.571+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'run_data_quality_check', 'scheduled__2025-07-25T19:00:00+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpa4ibifc0']
[2025-07-26T06:58:59.573+0700] {standard_task_runner.py:91} INFO - Job 303: Subtask run_data_quality_check
[2025-07-26T06:58:59.573+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=775) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T06:58:59.574+0700] {standard_task_runner.py:63} INFO - Started process 784 to run task
[2025-07-26T06:59:02.094+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.run_data_quality_check scheduled__2025-07-25T19:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T06:59:08.272+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='run_data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T19:00:00+00:00'
[2025-07-26T06:59:08.273+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T06:59:09.101+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T06:59:10.708+0700] {logging_mixin.py:188} INFO - Checking data quality for table: songplays
[2025-07-26T06:59:10.825+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T06:59:10.826+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 142, in data_quality_check
    raise ValueError(f"Data quality check failed for {table}. Table is empty!")
ValueError: Data quality check failed for songplays. Table is empty!
[2025-07-26T06:59:11.589+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=run_data_quality_check, run_id=scheduled__2025-07-25T19:00:00+00:00, execution_date=20250725T190000, start_date=20250725T235858, end_date=20250725T235911
[2025-07-26T06:59:11.912+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 303 for task run_data_quality_check (Data quality check failed for songplays. Table is empty!; 784)
[2025-07-26T06:59:13.341+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T06:59:15.176+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
