[2025-07-25T17:53:28.888+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table manual__2025-07-25T09:58:06.629719+00:00 [queued]>
[2025-07-25T17:53:29.088+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table manual__2025-07-25T09:58:06.629719+00:00 [queued]>
[2025-07-25T17:53:29.089+0700] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-25T17:53:29.334+0700] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_songplays_fact_table> on 2025-07-25 09:58:06.629719+00:00
[2025-07-25T17:53:29.349+0700] {standard_task_runner.py:60} INFO - Started process 17196 to run task
[2025-07-25T17:53:29.365+0700] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_songplays_fact_table', 'manual__2025-07-25T09:58:06.629719+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmp29kaw3tf']
[2025-07-25T17:53:29.370+0700] {standard_task_runner.py:88} INFO - Job 46: Subtask load_songplays_fact_table
[2025-07-25T17:53:33.468+0700] {task_command.py:423} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table manual__2025-07-25T09:58:06.629719+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-25T17:53:39.924+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T09:58:06.629719+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T09:58:06.629719+00:00'
[2025-07-25T17:53:39.926+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 163, in <lambda>
    python_callable=lambda: load_table(sql_queries.songplay_table_insert),
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'helpers.sql_queries' has no attribute 'songplay_table_insert'
[2025-07-25T17:53:41.035+0700] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=load_songplays_fact_table, execution_date=20250725T095806, start_date=20250725T105328, end_date=20250725T105341
[2025-07-25T17:53:41.441+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task load_songplays_fact_table (module 'helpers.sql_queries' has no attribute 'songplay_table_insert'; 17196)
[2025-07-25T17:53:41.490+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-25T17:53:42.447+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
