[2025-07-26T01:07:07.503+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T01:07:08.324+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T01:07:08.525+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T01:07:08.526+0700] {taskinstance.py:2306} INFO - Starting attempt 11 of 12
[2025-07-26T01:07:08.806+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_songs> on 2025-07-25 17:00:00+00:00
[2025-07-26T01:07:08.813+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'stage_songs', 'scheduled__2025-07-25T17:00:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmprrj52fll']
[2025-07-26T01:07:08.815+0700] {standard_task_runner.py:91} INFO - Job 224: Subtask stage_songs
[2025-07-26T01:07:08.815+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3429) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T01:07:08.815+0700] {standard_task_runner.py:63} INFO - Started process 3430 to run task
[2025-07-26T01:07:11.318+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T01:07:16.947+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T17:00:00+00:00'
[2025-07-26T01:07:16.948+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T01:07:18.857+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T01:07:19.458+0700] {logging_mixin.py:188} INFO - Found 71 song files.
[2025-07-26T01:07:19.678+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T01:07:19.679+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 59, in stage_songs_to_postgres
    cur.execute("""
psycopg2.errors.UndefinedColumn: column "file_path" of relation "loaded_files" does not exist
LINE 2:                     INSERT INTO loaded_files (file_path)
                                                      ^

[2025-07-26T01:07:20.427+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=stage_songs, run_id=scheduled__2025-07-25T17:00:00+00:00, execution_date=20250725T170000, start_date=20250725T180708, end_date=20250725T180720
[2025-07-26T01:07:20.756+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 224 for task stage_songs (column "file_path" of relation "loaded_files" does not exist
LINE 2:                     INSERT INTO loaded_files (file_path)
                                                      ^
; 3430)
[2025-07-26T01:07:23.146+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T01:07:24.124+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T01:07:24.222+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
