[2025-07-26T00:56:25.346+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T00:56:26.248+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T00:56:26.511+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T00:56:26.512+0700] {taskinstance.py:2306} INFO - Starting attempt 9 of 12
[2025-07-26T00:56:26.843+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_songs> on 2025-07-25 17:00:00+00:00
[2025-07-26T00:56:26.851+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'stage_songs', 'scheduled__2025-07-25T17:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmp5wpupovp']
[2025-07-26T00:56:26.853+0700] {standard_task_runner.py:91} INFO - Job 217: Subtask stage_songs
[2025-07-26T00:56:26.853+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3158) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T00:56:26.853+0700] {standard_task_runner.py:63} INFO - Started process 3175 to run task
[2025-07-26T00:56:31.913+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T00:56:37.002+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T17:00:00+00:00'
[2025-07-26T00:56:37.004+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T00:56:37.808+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T00:56:38.437+0700] {logging_mixin.py:188} INFO - Found 71 song files.
[2025-07-26T00:56:38.643+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T00:56:38.644+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 59, in stage_songs_to_postgres
    cur.execute("""
psycopg2.errors.UndefinedColumn: column "file_path" of relation "loaded_files" does not exist
LINE 2:                     INSERT INTO loaded_files (file_path)
                                                      ^

[2025-07-26T00:56:39.450+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=stage_songs, run_id=scheduled__2025-07-25T17:00:00+00:00, execution_date=20250725T170000, start_date=20250725T175626, end_date=20250725T175639
[2025-07-26T00:56:39.872+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 217 for task stage_songs (column "file_path" of relation "loaded_files" does not exist
LINE 2:                     INSERT INTO loaded_files (file_path)
                                                      ^
; 3175)
[2025-07-26T00:56:41.044+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T00:56:42.034+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
