[2025-07-25T18:44:47.425+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T18:44:48.239+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_events manual__2025-07-25T11:44:30.085491+00:00 [queued]>
[2025-07-25T18:44:48.475+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_events manual__2025-07-25T11:44:30.085491+00:00 [queued]>
[2025-07-25T18:44:48.476+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-25T18:44:48.715+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_events> on 2025-07-25 11:44:30.085491+00:00
[2025-07-25T18:44:48.754+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'stage_events', 'manual__2025-07-25T11:44:30.085491+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpebphgq6j']
[2025-07-25T18:44:48.761+0700] {standard_task_runner.py:91} INFO - Job 73: Subtask stage_events
[2025-07-25T18:44:48.765+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=19243) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T18:44:48.766+0700] {standard_task_runner.py:63} INFO - Started process 19248 to run task
[2025-07-25T18:44:51.532+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.stage_events manual__2025-07-25T11:44:30.085491+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-25T18:44:55.693+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='stage_events' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T11:44:30.085491+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T11:44:30.085491+00:00'
[2025-07-25T18:44:55.695+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T18:44:56.606+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-25T18:44:57.256+0700] {logging_mixin.py:188} INFO - Found 30 event files.
[2025-07-25T18:48:03.355+0700] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-25T18:48:03.355+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T18:48:04.786+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 61, in stage_events_to_postgres
    cur.execute("""
  File "/usr/lib/python3.12/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
    
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-07-25T18:48:04.899+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=stage_events, run_id=manual__2025-07-25T11:44:30.085491+00:00, execution_date=20250725T114430, start_date=20250725T114448, end_date=20250725T114804
