[2025-07-26T08:56:32.112+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T08:56:33.021+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_artist_dim_table scheduled__2025-07-25T15:00:00+00:00 [queued]>
[2025-07-26T08:56:33.294+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_artist_dim_table scheduled__2025-07-25T15:00:00+00:00 [queued]>
[2025-07-26T08:56:33.295+0700] {taskinstance.py:2306} INFO - Starting attempt 3 of 5
[2025-07-26T08:56:33.649+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_artist_dim_table> on 2025-07-25 15:00:00+00:00
[2025-07-26T08:56:33.655+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6506) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T08:56:33.657+0700] {standard_task_runner.py:63} INFO - Started process 6510 to run task
[2025-07-26T08:56:33.656+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_artist_dim_table', 'scheduled__2025-07-25T15:00:00+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmp5qy0_zgu']
[2025-07-26T08:56:33.658+0700] {standard_task_runner.py:91} INFO - Job 522: Subtask load_artist_dim_table
[2025-07-26T08:56:36.278+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_artist_dim_table scheduled__2025-07-25T15:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T08:56:40.266+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_artist_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T15:00:00+00:00'
[2025-07-26T08:56:40.268+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T08:56:41.454+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T08:56:42.363+0700] {sql.py:470} INFO - Running statement: 
    INSERT INTO artists (artistid, name, location, latitude, longitude)
    SELECT DISTINCT artist_id, artist_name, artist_location, artist_latitude, artist_longitude
    FROM staging_songs
    ON CONFLICT (artistid) DO NOTHING;
, parameters: None
[2025-07-26T08:56:42.509+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T08:56:42.510+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 104, in load_artists_table
    execute_sql(sql_queries.SqlQueries.artist_table_insert)
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 17, in execute_sql
    result = hook.run(sql_statement)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2025-07-26T08:56:43.231+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=load_artist_dim_table, run_id=scheduled__2025-07-25T15:00:00+00:00, execution_date=20250725T150000, start_date=20250726T015633, end_date=20250726T015643
[2025-07-26T08:56:46.069+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 522 for task load_artist_dim_table (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 6510)
[2025-07-26T08:56:47.160+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T08:56:49.025+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T08:56:49.087+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
